<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>RacingDemo</AssemblyName>
    <DefineConstants>$(DefineConstants);MONOGAME</DefineConstants>
    <TargetFramework>$(MonoGameTargetFramework)</TargetFramework>
    <OutputPath>bin\MonoGame.DesktopGL\$(Configuration)</OutputPath>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="$(MonoGameVersion)" />
    <PackageReference Include="Myra" Version="$(MyraVersion)" />
    <PackageReference Include="Nursia.MonoGame" Version="$(NursiaVersion)" />
  </ItemGroup>
  
  <ItemGroup>
    <None Update="Assets\**\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>
