/* Generated by MyraPad at 11/11/2025 6:10:50 AM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace RacingGame.UI
{
	partial class MainMenu: Panel
	{
		private void BuildUI()
		{
			_menuItemStartGame = new MenuItem();
			_menuItemStartGame.Text = "&Start Game";
			_menuItemStartGame.Id = "_menuItemStartGame";

			_menuHighscores = new MenuItem();
			_menuHighscores.Text = "&Highscores";
			_menuHighscores.Id = "_menuHighscores";

			_menuOptions = new MenuItem();
			_menuOptions.Text = "&Options";
			_menuOptions.Id = "_menuOptions";

			_menuQuit = new MenuItem();
			_menuQuit.Text = "&Quit";
			_menuQuit.Id = "_menuQuit";

			var verticalMenu1 = new VerticalMenu();
			verticalMenu1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			verticalMenu1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Center;
			verticalMenu1.LabelHorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Center;
			verticalMenu1.Items.Add(_menuItemStartGame);
			verticalMenu1.Items.Add(_menuHighscores);
			verticalMenu1.Items.Add(_menuOptions);
			verticalMenu1.Items.Add(_menuQuit);

			
			Widgets.Add(verticalMenu1);
		}

		
		public MenuItem _menuItemStartGame;
		public MenuItem _menuHighscores;
		public MenuItem _menuOptions;
		public MenuItem _menuQuit;
	}
}
