/* Generated by MyraPad at 11/12/2025 7:10:22 AM */
using Nursia;

namespace RacingDemo.UI
{
	public partial class OptionsWindow
	{
		public OptionsWindow()
		{
			BuildUI();

			_propertiesGraphics.Object = Nrs.GraphicsSettings;
			_propertiesDebug.Object = Nrs.DebugSettings;
			_propertiesEnvironment.Object = RacingGame.RenderEnvironment;
		}
	}
}